/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class JavaNum2aExample */

#ifndef _Included_JavaNum2aExample
#define _Included_JavaNum2aExample
#ifdef __cplusplus
extern "C" {
#endif
#undef JavaNum2aExample_FOCUS_TRAVERSABLE_UNKNOWN
#define JavaNum2aExample_FOCUS_TRAVERSABLE_UNKNOWN 0L
#undef JavaNum2aExample_FOCUS_TRAVERSABLE_DEFAULT
#define JavaNum2aExample_FOCUS_TRAVERSABLE_DEFAULT 1L
#undef JavaNum2aExample_FOCUS_TRAVERSABLE_SET
#define JavaNum2aExample_FOCUS_TRAVERSABLE_SET 2L
#undef JavaNum2aExample_TOP_ALIGNMENT
#define JavaNum2aExample_TOP_ALIGNMENT 0.0f
#undef JavaNum2aExample_CENTER_ALIGNMENT
#define JavaNum2aExample_CENTER_ALIGNMENT 0.5f
#undef JavaNum2aExample_BOTTOM_ALIGNMENT
#define JavaNum2aExample_BOTTOM_ALIGNMENT 1.0f
#undef JavaNum2aExample_LEFT_ALIGNMENT
#define JavaNum2aExample_LEFT_ALIGNMENT 0.0f
#undef JavaNum2aExample_RIGHT_ALIGNMENT
#define JavaNum2aExample_RIGHT_ALIGNMENT 1.0f
#undef JavaNum2aExample_serialVersionUID
#define JavaNum2aExample_serialVersionUID -7644114512714619750i64
#undef JavaNum2aExample_serialVersionUID
#define JavaNum2aExample_serialVersionUID 4613797578919906343i64
#undef JavaNum2aExample_INCLUDE_SELF
#define JavaNum2aExample_INCLUDE_SELF 1L
#undef JavaNum2aExample_SEARCH_HEAVYWEIGHTS
#define JavaNum2aExample_SEARCH_HEAVYWEIGHTS 1L
#undef JavaNum2aExample_OPENED
#define JavaNum2aExample_OPENED 1L
#undef JavaNum2aExample_serialVersionUID
#define JavaNum2aExample_serialVersionUID 4497834738069338734i64
#undef JavaNum2aExample_DEFAULT_CURSOR
#define JavaNum2aExample_DEFAULT_CURSOR 0L
#undef JavaNum2aExample_CROSSHAIR_CURSOR
#define JavaNum2aExample_CROSSHAIR_CURSOR 1L
#undef JavaNum2aExample_TEXT_CURSOR
#define JavaNum2aExample_TEXT_CURSOR 2L
#undef JavaNum2aExample_WAIT_CURSOR
#define JavaNum2aExample_WAIT_CURSOR 3L
#undef JavaNum2aExample_SW_RESIZE_CURSOR
#define JavaNum2aExample_SW_RESIZE_CURSOR 4L
#undef JavaNum2aExample_SE_RESIZE_CURSOR
#define JavaNum2aExample_SE_RESIZE_CURSOR 5L
#undef JavaNum2aExample_NW_RESIZE_CURSOR
#define JavaNum2aExample_NW_RESIZE_CURSOR 6L
#undef JavaNum2aExample_NE_RESIZE_CURSOR
#define JavaNum2aExample_NE_RESIZE_CURSOR 7L
#undef JavaNum2aExample_N_RESIZE_CURSOR
#define JavaNum2aExample_N_RESIZE_CURSOR 8L
#undef JavaNum2aExample_S_RESIZE_CURSOR
#define JavaNum2aExample_S_RESIZE_CURSOR 9L
#undef JavaNum2aExample_W_RESIZE_CURSOR
#define JavaNum2aExample_W_RESIZE_CURSOR 10L
#undef JavaNum2aExample_E_RESIZE_CURSOR
#define JavaNum2aExample_E_RESIZE_CURSOR 11L
#undef JavaNum2aExample_HAND_CURSOR
#define JavaNum2aExample_HAND_CURSOR 12L
#undef JavaNum2aExample_MOVE_CURSOR
#define JavaNum2aExample_MOVE_CURSOR 13L
#undef JavaNum2aExample_NORMAL
#define JavaNum2aExample_NORMAL 0L
#undef JavaNum2aExample_ICONIFIED
#define JavaNum2aExample_ICONIFIED 1L
#undef JavaNum2aExample_MAXIMIZED_HORIZ
#define JavaNum2aExample_MAXIMIZED_HORIZ 2L
#undef JavaNum2aExample_MAXIMIZED_VERT
#define JavaNum2aExample_MAXIMIZED_VERT 4L
#undef JavaNum2aExample_MAXIMIZED_BOTH
#define JavaNum2aExample_MAXIMIZED_BOTH 6L
#undef JavaNum2aExample_serialVersionUID
#define JavaNum2aExample_serialVersionUID 2673458971256075116i64
#undef JavaNum2aExample_EXIT_ON_CLOSE
#define JavaNum2aExample_EXIT_ON_CLOSE 3L
/*
 * Class:     JavaNum2aExample
 * Method:    num2aW
 * Signature: (D[B[B[B[BI)[B
 */
JNIEXPORT jbyteArray JNICALL Java_JavaNum2aExample_num2aW
  (JNIEnv *, jclass, jdouble, jbyteArray, jbyteArray, jbyteArray, jbyteArray, jint);

/*
 * Class:     JavaNum2aExample
 * Method:    get_num2aW
 * Signature: (D[B[B[B[BI)[B
 */
JNIEXPORT jbyteArray JNICALL Java_JavaNum2aExample_get_1num2aW
  (JNIEnv *, jclass, jdouble, jbyteArray, jbyteArray, jbyteArray, jbyteArray, jint);

/*
 * Class:     JavaNum2aExample
 * Method:    fnum2aW
 * Signature: (D[B[B[B[BI[B[B[B[BII)[B
 */
JNIEXPORT jbyteArray JNICALL Java_JavaNum2aExample_fnum2aW
  (JNIEnv *, jclass, jdouble, jbyteArray, jbyteArray, jbyteArray, jbyteArray, jint, jbyteArray, jbyteArray, jbyteArray, jbyteArray, jint, jint);

/*
 * Class:     JavaNum2aExample
 * Method:    get_fnum2aW
 * Signature: (D[B[B[B[BI[B[B[B[BII)[B
 */
JNIEXPORT jbyteArray JNICALL Java_JavaNum2aExample_get_1fnum2aW
  (JNIEnv *, jclass, jdouble, jbyteArray, jbyteArray, jbyteArray, jbyteArray, jint, jbyteArray, jbyteArray, jbyteArray, jbyteArray, jint, jint);

#ifdef __cplusplus
}
#endif
#endif
