gtkExample: bin
	gcc -Wall `pkg-config --cflags gtk+-3.0` src/gtkExampleEarlyBinding.c -o bin/gtkExampleEarlyBinding `pkg-config --libs gtk+-3.0` `pkg-config --libs gmodule-2.0` -L../../../build -lnum2a
bin:
	@mkdir -p bin
